FROM docker.io/library/alpine:3.22

COPY workload.sh /usr/local/bin/ploos-test-workload
RUN chmod 0755 /usr/local/bin/ploos-test-workload

VOLUME ["/data"]
ENTRYPOINT ["/usr/local/bin/ploos-test-workload"]
